server:
  port: 8080

spring:
  resources:
    static-locations: "classpath:/static/"
                                     
okta:
  oauth2:
    issuer: https://dev-115058.okta.com/oauth2/default
    clientId: 
    clientSecret:
    rolesClaim: groups